name: Unit test

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.app/Contents/Developer'
    - name: Run unit tests
      run: xcodebuild -scheme extensions -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 11' -configuration Debug test
