name: UnitTest

on: [push]

jobs:
  UnitTest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
    - name: Run unit tests
      run: xcodebuild -scheme extensions -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13' -configuration Debug test
