name: UnitTest

on: [push]

jobs:
  UnitTest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'
    - name: Run unit tests
      run: xcodebuild -scheme extensions -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' -configuration Debug test
